[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
name = "jobscriptgenerator"
requires-python = ">= 3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]