ALIASES = {
    "account": ["A"],
    "hold": ["H"],
    "input": ["i"],
    "job_name": ["N"],
    "licenses": ["L"],
    "mail_type": ["m"],
    "mail_user": ["M"],
    "ntasks": ["n"],
    "ntasks_per_node": ["mpiprocs"],
    "nodes": ["select"],
    "partition": ["q", "queue"],
    "quiet": ["Q"],
    "oversubscribe": ["s"],
    "time": ["t", "walltime"],
    "verbose": ["v"],
    "nodefile": ["F"],
    "nodelist": ["w"],
    "exclude": ["x"],
    "extra_node_info": ["B"],
}
